apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Release.Name }}-mysql-secret
  namespace: {{ .Release.Namespace }}
  annotations: 
    sealedsecrets.bitnami.com/cluster-wide: 'true'
spec:
  encryptedData:
    mysql_database: {{ .Values.secrets.mysql_database }}
    mysql_password: {{ .Values.secrets.mysql_password }}
    mysql_root_password: {{ .Values.secrets.mysql_root_password }}
    mysql_username: {{ .Values.secrets.mysql_username }}
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: {{ .Release.Name }}-mysql-secret
      namespace: {{ .Release.Namespace }}
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Release.Name }}-route53
  namespace: {{ .Release.Namespace }}
  annotations: 
    sealedsecrets.bitnami.com/cluster-wide: 'true'
spec:
  encryptedData:
    secret-access-key: {{ .Values.cert_manager.route53_secret_access_key }}
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: {{ .Release.Name }}-route53
      namespace: {{ .Release.Namespace }}
    type: Opaque